---
- name: Install OS-family-specific variables
  include_vars: "vars/{{ ansible_os_family }}.yml"

- name: Sanity check of ansible-postfix-aws's configuration
  assert:
    that:
      - postfix_aws_ses_username is defined
      - postfix_aws_ses_password is defined
      - postfix_aws_default_from_email is defined

- name: Sanity check of postfix_aws_sender_canonical_maps variable
  assert:
    that:
      - "'pattern' in item"
      - "'address' in item"
  with_items: "{{ postfix_aws_sender_canonical_maps }}"

- name: Install Postfix
  package: name=postfix state=present

- name: Ensure Postfix is enabled and started
  service: name=postfix enabled=yes state=started

- name: Install OS-family-specific packages
  include_tasks: "tasks/{{ ansible_os_family }}.yml"

- name: Configure Postfix main.cf
  lineinfile:
    backup: yes
    dest: /etc/postfix/main.cf
    regexp: "^{{ item.variable }}\ ="
    line: "{{ item.variable }} = {{ item.value }}"
    state: present
  with_items:
    - { variable: 'relayhost', value: "[{{ postfix_aws_ses_host }}]:{{ postfix_aws_ses_port }}" }
    - { variable: 'smtp_sasl_auth_enable', value: 'yes' }
    - { variable: 'smtp_sasl_security_options', value: 'noanonymous' }
    - { variable: 'smtp_sasl_password_maps', value: 'hash:/etc/postfix/sasl_passwd' }
    - { variable: 'smtp_use_tls', value: 'yes' }
    - { variable: 'smtp_tls_security_level', value: 'encrypt' }
    - { variable: 'smtp_tls_note_starttls_offer', value: 'yes' }
    - { variable: 'smtp_tls_CAfile', value: '{{ postfix_aws_tls_cafile_path }}' }
    - { variable: 'sender_canonical_maps', value: 'regexp:/etc/postfix/sender_canonical' }
  notify: Restart Postfix

- name: Create file with SMTP credentials
  lineinfile:
    backup: yes
    create: yes
    dest: /etc/postfix/sasl_passwd
    regexp: "{{ postfix_aws_ses_host }}"
    line: "[{{ postfix_aws_ses_host }}]:{{ postfix_aws_ses_port }} {{ postfix_aws_ses_username }}:{{ postfix_aws_ses_password }}"
    state: present
  register: postfix_aws_credentials_res
  notify: Restart Postfix

- name: Create a hashmap database file with SMTP credentials
  command: postmap hash:/etc/postfix/sasl_passwd
  when: postfix_aws_credentials_res.changed

- name: Set permissions and owner of created files
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - /etc/postfix/sasl_passwd.db
    - /etc/postfix/sasl_passwd

- name: Set canonical mappings for sender addresses
  template:
    src: etc/postfix/sender_canonical.j2
    dest: /etc/postfix/sender_canonical
    backup: yes
  notify: Reload Postfix
